### ISSUE TITLE
numpy arrays as input don't work

### ISSUE THREAD

**Issue by MichaelSchreier** [vc1492a/PyNomaly#10]
Using `data = pd.DataFrame(np.random.rand(100, 5))` as the input to `LocalOutlierProbability` works as expected, however, passing the raw ndarray `np.random.rand(100, 5)` throws an error: 
`self.points_vector = self.data.reshape(self.data.shape[1:])
ValueError: cannot reshape array of size 500 into shape (5,)`

**Comment by vc1492a** [comment]
@MichaelSchreier thanks for identifying and opening the issue. This bug has been addressed in the [dev](https://github.com/vc1492a/PyNomaly/tree/dev) and will be in the next release.
