### ISSUE TITLE
Clarify orientation of 2d array

### ISSUE THREAD

**Issue by llllllllll** [vc1492a/PyNomaly#19]
It might help to mention what the semantic orientation of the input data array is. Originally I had it transposed which gave me a somewhat unhelpful index error. If you have a square array, maybe for testing, you might not realize that the data is flipped.

**Comment by vc1492a** [comment]
@llllllllll I added a clarifying example to `readme.md` that states clearly the orientation of the input array in [this commit](https://github.com/vc1492a/PyNomaly/commit/770523220f78a1592a210a143c0da604f0455103). If you feel additional clarification is needed, please feel free to submit a pr with the changes. Thanks!
