### ISSUE TITLE
data stream

### ISSUE THREAD

**Issue by ali-Eskandarian** [vc1492a/PyNomaly#48]
Is this package suitable for stream data? 
By stream data I mean An array of data that is constantly producing and I want to find an anomaly as soon as it appears.

**Comment by vc1492a** [comment]
Hi @ali-Eskandarian. Yes, one LoOP-related algorithm is implemented. Please see the readme.md for an implementation of a streaming version of the Local Outlier Probabilities (LoOP) algorithm that can be used with streaming data.
