### ISSUE TITLE
ImportError: cannot import name 'assert_greater' from 'sklearn.utils._testing'

### ISSUE THREAD

**Issue by NicoleRR** [vc1492a/PyNomaly#50]
I would like to ask whether this function（assert_greater） is defined by you yourself or in which python library class.

**Comment by vc1492a** [comment]
> I would like to ask whether this function（assert_greater） is defined by you yourself or in which python library class.

@NicoleRR, this function is part of the `scikit-learn` library and is not written by this repository's authors.
