### ISSUE TITLE
Support Installation in conda environments without pip

### ISSUE THREAD

**Issue by vc1492a** [vc1492a/PyNomaly#52]
This possibility to be explored.

**Comment by IroNEDR** [comment]
Just leaving this comment here for future documentation:
Currently the conda docs recommend using the `conda skeleton pypi <your_package>`  to generate the conda recipe from an existing pypi package but the skeleton seems to be buggy and not well maintained as [described in this issue](https://github.com/conda/conda-build/issues/5258). So I will instead use the newer tool called [grayskull ](https://github.com/conda/grayskull) for that.

**Comment by vc1492a** [comment]
> Just leaving this comment here for future documentation: Currently the conda docs recommend using the `conda skeleton pypi <your_package>` to generate the conda recipe from an existing pypi package but the skeleton seems to be buggy and not well maintained as [described in this issue](https://github.com/conda/conda-build/issues/5258). So I will instead use the newer tool called [grayskull ](https://github.com/conda/grayskull) for that.

Looks like a great alternative, thanks for sharing.

**Comment by vc1492a** [comment]
@IroNEDR for documentation's sake, noting here that the `readme.md` will be updated by @IroNEDR with the appropriate download instructions for conda environments.
